### ISSUE TITLE
"webpack2-validator": "^1.0.0"   throws error

### ISSUE THREAD

**Issue by 462960** [bultas/minimal#2]
Hi, Bultas!
It's, definitely, my fault but I'm asking for a hand;
I've tried your webpack.config.js and validator throws the same errors as does on my config.
![webpackmistake](https://cloud.githubusercontent.com/assets/10447862/23945162/1e4ad2e0-097e-11e7-9ac8-944e6b565228.png)
Migrating to wepack2 turned to be painful for me.
I have installed
 "webpack": "^2.2.1",
   "webpack-dev-server": "^2.4.2",
    "webpack2-validator": "^1.0.0" 
Any help is welcome.

**Comment by bultas** [comment]
It seems that Validator wants you to add some loaders.. but in this project, none is needed. 
Try add `"loaders": []` .. should works

**Comment by 462960** [comment]
No way: "rules" is not allowed, for now. But "rules" for W2 is the same as "loaders" for W. So, I'm in doubt, whether I'm using W2?
pacage.json says it's up to date
![w2-walidator](https://cloud.githubusercontent.com/assets/10447862/24752262/ba37233a-1ad5-11e7-897d-0283fe336f5e.png)
But even your, Butlas, webpack.config.js does not work.

**Comment by bultas** [comment]
You are right.. sorry. 
So follow documentation and add loaders into rule
https://webpack.js.org/concepts/loaders/#configuration

```
 module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          { loader: 'style-loader'},
          {
            loader: 'css-loader',
            options: {
              modules: true
            }
          }
        ]
      }
    ]
  }
```

Second thing.. 
I don't understand why are you using any validator if Webpack 2 has own validation.

**Comment by 462960** [comment]
Thanks a lot. But output looks suspiciously like I still have WP the first which does not know about "rules", so requires "loaders". Another word, doesn't work. 
As for validator. Without it, your app just doesn't work with some vague clue in terminal. WP Validator tells about the exact typo.

**Comment by bultas** [comment]
Doesnt work? what operation system you use? I test it on Linux and OSX and work ok.

**Comment by 462960** [comment]
Works fine, for now, thanks to Juho. Does not see styles but I'll fix it, reading docs. Thank you, Butlas, have a nice weekend!
